---
output: html_document
---


### Source Information
*This section references the data collected, the sources of collection, and the data manipulation.*  

**Data Collection**: 

1. Confirmed Cases of COVID-19
2. Confirmed deaths from COVID-19
3. Air Force base name, MAJCOM, location, and state
4. US county FIPS codes, location, state, population, land area
5. Hospital FIPS codes, location, state, number of beds, type
6. Distance matrices for counties and hospitals related to each CONUS Air Force installation (preemptively created for this analysis)

**Data Sources**: 

1. **https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/** : This website provides daily updated information every morning of cases and deaths from the coronavirus in every county around the U.S. The data does not include secondary effects such as deaths from lack of treatment due to hospital capacity, rather it only included deaths of individuals with COVID-19. 

2. **https://covid19.healthdata.org/projections** : This website houses the data produced by the IHME model. Projections are recorded for every state, and updated daily.  

3. **https://www.ahd.com/state_statistics.html** : The American Hospital Directory (AHD) contains stats for all non-federal, short term, acute care hospitals in every state. Data includes number of staffed beds along with total discharges and total patient days. These metrics are used to estimate an average hospital utilization.

4. **https://github.com/treypujats/COVID19** : Loaded on this repository is static data regarding Air Force installations, US county data, hospital data, and distance matrices between hospitals and bases as well as counties and bases. The Air Force installation data, and US county data are pulled from Major Adam Messer's github account and stored locally to ensure no changes are made to the file path or data. Thank you Major Messer for providing data and helping us get started with the analysis. 

**Data Manipulation**: 

1. **Distance matrices**: Distance matrices were created to limit the local area around an installation. Major Freels (AFIT) helped build these matrices to measure relative mileage distance between base and county as well as base and hospital. The distances are calculated using geospatial coordinates (latitude, longitude) to measure distance and store in a matrix.

